version: '3'
services:
  app:
    image: ansible-ui:latest
    container_name: ansible-ui-app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
      - ADMIN_USERNAME=admin123
      - ADMIN_PASSWORD=admin123
    volumes:
      # 如果需要持久化数据库，取消下面注释
      # - ./instance:/app/instance
      # 如果需要持久化 SSH key，取消下面注释
      # - ./ssh_keys:/root/.ssh
      - /etc/localtime:/etc/localtime:ro
